#create a persistant volume claim and data
#
#
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myegs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


