# To create a pod and install ansible.
#
kind: Pod
apiVersion: v1
metadata:
  name: ansibletestpod
spec:
  containers:
    - name: ansiblecontr
      image: ansible/ansible:ubuntu-22.04
      command: ["/bin/bash","-c","while true; do echo hello-ansible echo ansible --version; sleep 5; done"]
