# To create a pod with Nginx image and container.
#
#
#
kind: Pod
apiVersion: v1
metadata:
  name: nginx-web-testpod
  labels:
    app : webserver
    environment: dev1
spec:
  containers:
    - name: nginxwebxx
      image: nginx:latest
      ports:
        - containerPort: 80

