##creating a first pod and container
#
kind: Pod
apiVersion: v1
metadata: 
 name: testpod
spec:
 containers:
   - name: co1
     image: ubuntu
     command: ["/bin/bash","-c","while true; do echo Hello- Kubernetes!; sleep 5; done;"] 
